// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avxvritfxevmpjsfamhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2eHZyaXRmeGV2bXBqc2ZhbWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODE2NDEsImV4cCI6MjA3MTM1NzY0MX0.f3hsTas44dBlwV0csJUwDhOkCGD-eJdBaqgJPSMSJwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});